# This is the default format. 
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title 

exclude: 
  - .rvmrc
  - .rbenv-version
  - README.md
  - Rakefile
  - changelog.md
  - bower_components
  - node_modules
  - src

highlighter: pygments

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : Strayegg
tagline: Hobo-egg was here
author :
  name : Simon Hooker
  email : simon@mso.net
  github : SimonHooker
  twitter : SimonHooker

production_url : http://www.strayegg.com

strayegg :

  comments :
    provider : disqus
    disqus :
      short_name : strayegg

  analytics :
    provider : google 
    google : 
        tracking_id : 'UA-38996619-2'

