
permalink: /:year/:month/:day/:title 

exclude: 
  - .rvmrc
  - .rbenv-version
  - README.md
  - Rakefile
  - changelog.md
  - bower_components
  - node_modules
  - src

highlighter: pygments

title : Strayegg
tagline: Hobo-egg was here
author :
  name : Simon Hooker
  email : simon@mso.net
  github : SimonHooker
  twitter : SimonHooker
  disqus : strayegg
  analytics : 'UA-38996619-2'

production_url : http://www.strayegg.com
